### ISSUE TITLE
How do you tie a trigger to an action?

### ISSUE THREAD

**Issue by mkaatman** [Anonym-tsk/zigbee2mqtt-extensions#1]
First, this project is neat. Thanks for putting it together.

What I'm trying to do:
Tie a contact sensor state to a bulb.

contact: false = bulb on
contact: true = bulb off

What I've tried so far:
```yaml
automations:
  automation_by_state:
    trigger:
      platform: state
      entity: pantry_door_switch
      attribute: contact
      state: false
    action:
      - entity: pantry_bulb
        service: turn_on
      - entity: pantry_bulb
        service: turn_off
```

This is toggling the bulb on each open. I'm having difficulty understanding how to add a trigger for state: true and tie it to the 2nd action. Any guidance would be appreciated!

**Comment by senilio** [comment]
This should do the trick

```yaml
automations:
  automation_pantry_bulb_on:
    trigger:
      platform: state
      entity: pantry_door_switch
      attribute: contact
      state: false
    action:
      - entity: pantry_bulb
        service: turn_on
  automation_pantry_bulb_off:
    trigger:
      platform: state
      entity: pantry_door_switch
      attribute: contact
      state: true
    action:
      - entity: pantry_bulb
        service: turn_off
```
