### ISSUE TITLE
Timed actions

### ISSUE THREAD

**Issue by DieterKoblenz** [Anonym-tsk/zigbee2mqtt-extensions#12]
Would it be possible to include actions with a timer or pauze in between? For example. When I close a door, I'd like to light to go off after 5 minutes.

**Comment by Anonym-tsk** [comment]
Look at this example
```yaml
trigger:
  platform: state
  state: OFF
  entity: My Door
  for: 300
```
