### ISSUE TITLE
Single automation for different buttons with multiple gang switches

### ISSUE THREAD

**Issue by Nikolay-Ch** [Anonym-tsk/zigbee2mqtt-extensions#13]
Hi!
I need to create automation with this behaviour:
- if I press left button on first switch then turn on right button on second switch
- if I press right button on second switch then turn on left button on first switch

I want to do it in one automation like this:
```yml
automation_by_state_3:
  trigger:
    platform: state
    entity:
      - "FirtshSwitch"
      - "SecondSwitch"
    attribute:
      - state_right
      - state_left
    state: ON
  action:
    - entity: "FirstSwitch"
      service: custom
      data:
        state_right: ON
    - entity: "SecondSwitch"
      service: custom
      data:
        state_left: ON
```

But now this automation not supported double attribute key...

**Comment by Anonym-tsk** [comment]
```yaml
automation_1:
  trigger:
    platform: state
    entity:
      - "FirtshSwitch"
    attribute:
      - state_left
    state: ON
  action:
    - entity: "SecondSwitch"
      service: custom
      data:
        state_right: ON
automation_2:
  trigger:
    platform: state
    entity:
      - "SecondSwitch"
    attribute:
      - state_right
    state: ON
  action:
    - entity: "FirstSwitch"
      service: custom
      data:
        state_left: ON
```
