### ISSUE TITLE
Transfer a value of one device to another

### ISSUE THREAD

**Issue by Burki24** [Anonym-tsk/zigbee2mqtt-extensions#16]
The desire for a new function:

Will it be possible in a further version to transmit values (e.g. a room thermostat) to another device (e.g. a radiator thermostat)?

The idea behind it:
The Bosch thermostats (https://www.zigbee2mqtt.io/devices/BTH-RA.html) make it possible to use a temperature from an external sensor (instead of the integrated one). Unfortunately it is not possible to achieve this via bindings.

Therefore, this option in the extension would be very desirable.

**Comment by Anonym-tsk** [comment]
You can make simple automation if-else.
For example:
```yaml
thermostat:
  trigger:
    platform: numeric_state
    entity: Temperature Sensor
    attribute: temperature
    above: 25
    for: 60
  action:
    - entity: Thermostat
      service: turn_off
```
